import { Product } from "@/types/product";

export const FEATURED_PRODUCTS_SECTION = {
    badge: "✨ Featured Products",
    title: "Crown Your Beauty",
    description:
        "Discover our most loved products designed to make every young queen feel beautiful, confident, and absolutely radiant ✨",
    viewAllButton: "View All Products",
};

export const FEATURED_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Premium Fleece Hoodie",
        price: 24.99,
        originalPrice: 29.99,
        rating: 4.8,
        reviews: 124,
        images: ["/assets/B1.jpg"],
        badge: "Bestseller",
        badgeColor: "from-green-400 to-emerald-500",
        description: "A cozy fleece hoodie for everyday comfort.",
        features: ["Soft fleece", "Front pocket", "Adjustable hood"],
        ingredients: [],
        inStock: true,
        category: "tops",
    },
    {
        id: "2",
        name: "Classic Comfort Trousers",
        price: 18.99,
        originalPrice: 22.99,
        rating: 4.9,
        reviews: 89,
        images: ["/assets/B2.jpg"],
        badge: "New",
        badgeColor: "from-blue-400 to-cyan-500",
        description: "Classic trousers for all-day comfort.",
        features: ["Elastic waistband", "Breathable fabric"],
        ingredients: [],
        inStock: true,
        category: "bottoms",
    },
    {
        id: "3",
        name: "Soft Cotton T-shirt",
        price: 32.99,
        originalPrice: 39.99,
        rating: 4.7,
        reviews: 156,
        images: ["/assets/H1.jpg"],
        badge: "Sale",
        badgeColor: "from-red-400 to-pink-500",
        description: "Soft cotton t-shirt for everyday wear.",
        features: ["100% cotton", "Tagless label"],
        ingredients: [],
        inStock: true,
        category: "tops",
    },
];
