import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import PromoBarWrapper from "@/components/layout/promo-bar-wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <Header />
                <PromoBarWrapper />
                {children}
            </body>
        </html>
    );
}
